# Generated by Django 4.0.6 on 2022-07-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_user_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_content', models.CharField(max_length=300)),
                ('img_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
