# Generated by Django 4.1 on 2022-08-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('imgfolder_no', models.IntegerField()),
                ('img_no', models.IntegerField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
            ],
        ),
    ]
