# Generated by Django 4.1 on 2022-08-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_letter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='imgfolder_no',
            field=models.IntegerField(null=True),
        ),
    ]
