# Generated by Django 4.1 on 2022-08-11 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_refreshtoken'),
        ('letterapp', '0004_alter_letter_img_no_alter_letter_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
