# Generated by Django 4.0.5 on 2022-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0006_letter_letter_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_from',
            field=models.CharField(default='익명', max_length=100),
        ),
    ]
