# Generated by Django 4.1 on 2022-08-11 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30)),
                ('provider', models.CharField(max_length=20)),
                ('birth', models.DateField(blank=True)),
                ('refreshToken', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
