# Generated by Django 4.1 on 2022-08-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_is_active_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
