# Generated by Django 4.0.5 on 2022-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.CharField(choices=[('lp', 'lightpink'), ('p', 'pink'), ('or', 'orange'), ('y', 'yellow'), ('g', 'green'), ('lb', 'lightblue'), ('b', 'blue'), ('pu', 'purple')], default='lightpink', max_length=2),
        ),
    ]
