# Generated by Django 4.0.5 on 2022-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_user_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(choices=[('lp', '#FE4179'), ('p', '#FF6161'), ('or', '#FE7B1D'), ('y', '#6C6C6C'), ('g', '#42B494'), ('lb', '#1786DB'), ('b', '#3753C0'), ('pu', '#7341C3')], default='lp', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.CharField(choices=[('lp', '#FFEFF3'), ('p', '#FFDDDD'), ('or', '#FFEED9'), ('y', '#FE7B1D'), ('g', '#FFF8CC'), ('lb', '#D8EEFF'), ('b', '#E2E8FF'), ('pu', '#EDE9FF')], default='lp', max_length=2),
        ),
    ]
