# Generated by Django 4.0.6 on 2022-08-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.CharField(choices=[('lp', '#FFEFF3'), ('p', '#FFDDDD'), ('or', '#FFEED9'), ('y', '#FFF8CC'), ('g', '#FFF8CC'), ('lb', '#D8EEFF'), ('b', '#E2E8FF'), ('pu', '#EDE9FF')], default='lp', max_length=2),
        ),
    ]
