"""
Django settings for rememB project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from operator import truediv
from pathlib import Path
from pickle import TRUE
from decouple import config
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
    '1.0.0.127.in-addr.arpa',
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'partyroomapp',
    'letterapp',
    'balanceapp',
    'userapp',

    #restframework
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',

    'corsheaders',
]

REST_FRAMEWORK = { 
    # 헤더에 access token을 포함하여 유효한 유저만이 접근이 가능하는 것을 Default로 설정
    'DEFAULT_PERMISSION_CLASSES': ( 
       'rest_framework.permissions.IsAuthenticated',
    ),
    # 권한 설정
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'userapp.authenticate.SafeJWTAuthentication',
    ]
}

REST_USE_JWT=TRUE

SIMPLE_JWT={
    'ACCESS_TOKEN_LIFETIME':datetime.timedelta(minutes=50),
    'REFRESH_TOKEN_LIFETIME':datetime.timedelta(days=1),
    'ROTATE_REFRESH_TOKENS':False,
    'TOKEN_USER_CLASS':'userapp.User',
    #'USER_ID_FIELD':'email',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #최상단에 추가해주기
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rememB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rememB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

CORS_ALLOWED_ORIGINS = [
	# 허용할 Origin 추가
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://43.200.193.74:8000",
    "http://43.200.193.74:3000",
    "http://rememb.site:3000",
    "http://rememb.site:8000",
]


CORS_ORIGIN_ALLOW_ALL = False

# 접근 가능한 url 을 따로 관리
CORS_ORIGIN_WHITELIST = ('http://127.0.0.1:8000', 'http://localhost:3000')

CORS_ALLOW_CREDENTIALS = True